### ISSUE TITLE
The standard TLauncher redownload issue

### ISSUE THREAD

**Issue by RaidhoSketch** [makamys/MCLib#2]
Yes, we know, it's written in the wiki, but we are clearly missing some key knowledge because every JVM flag variation to change the directory location we try is rejected, so please, please type the example flag that works.

**Comment by Roadhog360** [comment]
TLauncher is not supported iirc, exactly because of issues like this. (Also piracy)
I might be wrong tho

**Comment by RaidhoSketch** [comment]
Well, we read this: "// The old launcher deletes extra files from the assets directory, so we can't live there. Use `<launcher work dir>/asset_director` instead. " in, like, the actual code of this thing, so it's not only TLauncher that does it.

**Comment by makamys** [comment]
Here's an example: `-Dminecraft.sharedDataDir="C:/example/minecraft_shared_data"`

You know it works if you see this line in the log:
`Using directory C:\example\minecraft_shared_data`

> TLauncher is not supported iirc

It's not *explicitly* supported, but this is just a general question about how to change the download directory.

Also if someone submitted a PR that adds TLauncher support I'd be willing to merge it (it's possible that only `AssetDirector#isOldLauncher` would need to be changed for this).

**Comment by RaidhoSketch** [comment]
Ok, we've tried it a few times, it does register as a correct argument if we don't modify the last step, and shows up in logs, but that's the only good news. First, it doesn't show up in the JVM list (despite any specified path) (for the record, the latest one used this: -Dminecraft.sharedDataDir="C:/shareddata/minecraft_shared_data"), and thus _this_ also happens: Using directory C:\Users\User\AppData\Roaming\\.minecraft\assets\asset_director, which, well, fuck.

Including the full log here: [latest.log](https://github.com/makamys/MCLib/files/11327088/latest.log)

(did not mean to press on that)

**Comment by Roadhog360** [comment]
That command contains "Roaming.minecraft", it should be "Roaming/.minecraft" (or \)

**Comment by RaidhoSketch** [comment]
That was a typo (and of the output anyways).

**Comment by makamys** [comment]
That sounds like a TLauncher issue, I'm unable to help with that. But you can avoid the need to use a JVM flag by [setting an environmental variable](https://www.computerhope.com/issues/ch000549.htm) instead (named `MINECRAFT_SHARED_DATA_DIR`). I have a user variable set myself.

**Comment by makamys** [comment]
Actually looking at the log again, it seems you set it as a *program argument*, not a JVM argument. 

`Completely ignored arguments: [-Dminecraft.sharedDataDir, C:/shareddata/minecraft_shared_data,`

Based on this image I found on TLauncher's website, there should be a separate "JVM arguments" field, make sure you set that one and not the "Minecraft arguments" field.

![](https://tlauncher.org/img/tlauncher-2.0-settings-en.png)

**Comment by RaidhoSketch** [comment]
Yeah, might use the variable anyway, because they deleted this field in later releases: 
![image](https://user-images.githubusercontent.com/73392166/234558275-60c90431-0906-4c68-aa7c-e6803594ab44.png)

Upd: Did it, worked perfectly. Many thanks.
